<!--SEL INFORMATION-->
<div class="block block-information">
  <div class="block-title">
        <strong><span>Store Information</h3></span></strong>
    </div>
         <div class="block-content"> 
								
								<ul>
								  <?php
	                                  echo $this->getLayout()->createBlock('cms/block')->setBlockId('store_inform')->toHtml() 
                                  ?>
								</ul>
          </div>

</div>
<!--END OF SEL INFORMATIONS-->